export enum Role {
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  RESPONSABLE = 'ROLE_RESPONSABLE',
  ADMIN = 'ROLE_ADMIN',
  EMPLOYEE = 'ROLE_EMPLOYEE',
  USER = 'ROLE_USER',
  Client= 'ROLE_CLIENT'
}
